const allSubjects = [
  "Additional Mathematics",
  "Agriculture Science",
  "Art",
  "Biology",
  "Building Technology",
  "Caribbean Studies",
  "Chemistry",
  "Computer Science / Programming",
  "Drama / Theatre Arts",
  "Economics",
  "Electrical and Electronic Technology",
  "English A (General Proficiency)",
  "English B (Second Language)",
  "Environmental Science",
  "Food and Nutrition",
  "French",
  "Geography",
  "History (Caribbean or World)",
  "Human and Social Biology (HSB)",
  "Information Technology (IT)",
  "Mechanical Engineering Technology",
  "Music",
  "Office Administration",
  "Physical Education",
  "Principles of Accounts",
  "Principles of Business",
  "Portuguese",
  "Religious Education (RE)",
  "Social Studies",
  "Technical Drawing",
  "Visual Arts"
].sort()